-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIQtggZ2mG+BAU5KT
dqMNtHlBxhyd+arftbSK8rfMZiegCgYIKoZIzj0DAQehRANCAAQay+0XgTLZfJrP
ROSQwPqZIIodjHa16MbMdq2HmKb6nYWQfNaE5TbYBuzC31nkGl7D3oF/I3AhstnF
iDYwoQWa
-----END PRIVATE KEY-----